### ISSUE TITLE
Get familiar with current SBF-SEM

### ISSUE THREAD

**Issue by OmarAlAkkad** [oss-slu/SBFSEM-tools#3]

**Comment by OmarAlAkkad** [comment]
It seems the code can run using matlab online but some errors pop up.

**1- When closing RenderApp:**
Warning: The following error was caught while executing 'uiextras.jTree.TreeNode' class destructor:
Error using uiextras.jTree.Tree/removeNode
Java exception occurred:
java.lang.ArrayIndexOutOfBoundsException: 0
	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:388)
	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:397)
	at com.mathworks.peermodel.impl.PeerNodeImpl.getChild(PeerNodeImpl.java:399)
	at com.mathworks.matlabserver.jcp.handlers.tableHandlers.TreeModelHandler.removeChildNode(TreeModelHandler.java:151)
	at com.mathworks.matlabserver.jcp.handlers.tableHandlers.TreeModelHandler.treeNodesRemoved(TreeModelHandler.java:56)
	at javax.swing.tree.DefaultTreeModel.fireTreeNodesRemoved(DefaultTreeModel.java:548)
	at javax.swing.tree.DefaultTreeModel.nodesWereRemoved(DefaultTreeModel.java:328)
	at javax.swing.tree.DefaultTreeModel.removeNodeFromParent(DefaultTreeModel.java:262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.mathworks.jmi.AWTUtilities$Invoker$3$1.call(AWTUtilities.java:525)
	at com.mathworks.mvm.context.ThreadContext.callWithContext(ThreadContext.java:105)
	at com.mathworks.mvm.context.MvmContext.callWithContext(MvmContext.java:113)
	at com.mathworks.jmi.AWTUtilities$Invoker$3.runWithOutput(AWTUtilities.java:522)
	at com.mathworks.jmi.AWTUtilities$Invoker$2.watchedRun(AWTUtilities.java:475)
	at com.mathworks.jmi.AWTUtilities$WatchedRunnable.run(AWTUtilities.java:436)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Error in uiextras.jTree.TreeNode/updateParent (line 368)
                    nObj.Tree.removeNode(nObj, nObj.Parent);

Error in uiextras.jTree.TreeNode/set.Parent (line 463)
            newParent = updateParent(nObj,newParent);

Error in uiextras.jTree.TreeNode/delete (line 144)
            nObj.Parent(:) = [];

Error in uiextras.jTree.TreeNode/delete (line 142)
            delete(nObj.Children(isvalid(nObj.Children)))

Error in uiextras.jTree.Tree/delete (line 284)
            delete(tObj.Root);

Error in uiextras.jTree.Tree>@(src,e)delete(tObj) (line 483)
                'DeleteFcn',@(src,e)delete(tObj),... 
> In uiextras.jTree/TreeNode/delete (line 142)
In uiextras.jTree/Tree/delete (line 284)
In uiextras.jTree.Tree>@(src,e)delete(tObj) (line 483)
In closereq (line 18) 

**2- When selecting "Table" in GraphApp:**
Unrecognized function or variable 'AnnotationTableView'.

Error in GraphApp/createTableTab (line 841)
            AnnotationTableView(obj);

Error in GraphApp/onChangedTab (line 543)
                obj.createTableTab(evt.NewValue);

Error in GraphApp>@(varargin)obj.onChangedTab(varargin{:}) (line 675)
                'SelectionChangedFcn', @obj.onChangedTab);
 
Error while evaluating TabGroup SelectionChangedFcn.

Unrecognized function or variable 'AnnotationTableView'.

Error in GraphApp/createTableTab (line 841)
            AnnotationTableView(obj);

Error in GraphApp/onChangedTab (line 543)
                obj.createTableTab(evt.NewValue);

Error in GraphApp>@(varargin)obj.onChangedTab(varargin{:}) (line 675)
                'SelectionChangedFcn', @obj.onChangedTab);
 
Error while evaluating TabGroup SelectionChangedFcn.

**3- App in general is very slow** -> code optimization? matlab online is slow? huge data?

**4- When importing the neurons with synapses, a loading bar shows. Clicking on the x to stop importing and close the bar does nothing. (bug in code? bug in matlab?)**
